services:

    casebox_core.event_listener.exception_listener:
        class: Casebox\RpcBundle\EventListener\ExceptionListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
