services:

    casebox_core.event_listener.exception_listener:
        class: Casebox\RpcBundle\EventListener\ExceptionListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    casebox_rpc.event_listener.rpc_api_default_config_listener:
        class: Casebox\RpcBundle\EventListener\RpcApiDefaultConfigListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }