services:
    casebox_rpc.service.rpc_api_service:
        class: Casebox\RpcBundle\Service\RpcApiService
        calls:
            - [ setContainer, [ "@service_container" ] ]

    casebox_rpc.service.rpc_api_config_service:
        class: Casebox\RpcBundle\Service\RpcApiConfigService
